# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: hashicorp/packer-plugin-vsphere/build_plugin_binaries
permissions:
  contents: read
on:
  push:
    branches:
    - main
jobs:
  build_linux:
    defaults:
      run:
        working-directory: ~/go/src/github.com/hashicorp/packer-plugin-vsphere
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.20
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: amd64
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: arm
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: arm64
